#!/usr/bin/env bash
set -euo pipefail

# Generates a local .env file with resource hints derived from detected hardware.
# This is best-effort and optional; podman-compose should still work without it.

ENV_FILE="${ENV_FILE:-.env}"

mem_total_mb() {
  if [[ -r /proc/meminfo ]]; then
    awk '/^MemTotal:/ {printf "%d\n", int($2/1024)}' /proc/meminfo
    return 0
  fi
  echo 0
}

cpu_cores() {
  getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1
}

detect_arch() {
  uname -m 2>/dev/null || echo unknown
}

detect_gpu() {
  if [[ -e /dev/nvidia0 ]]; then
    echo cuda
    return
  fi
  if [[ -d /dev/dri ]]; then
    echo dri
    return
  fi
  echo none
}

# Policy (matches README):
# - RAM: 50% of available, min 300MB, max 600MB
# - CPU: 1–2 cores depending on system size
TOTAL_MB=$(mem_total_mb)
CORES=$(cpu_cores)
ARCH=$(detect_arch)
GPU=$(detect_gpu)

if [[ "$TOTAL_MB" -gt 0 ]]; then
  RAM_MB=$(( TOTAL_MB / 2 ))
else
  RAM_MB=600
fi

if [[ "$RAM_MB" -lt 300 ]]; then RAM_MB=300; fi
if [[ "$RAM_MB" -gt 600 ]]; then RAM_MB=600; fi

CPU_LIMIT="1.0"
CPU_RESERVATION="0.5"
if [[ "$CORES" -gt 2 ]]; then
  CPU_LIMIT="2.0"
fi

MEM_LIMIT="${RAM_MB}M"
MEM_RESERVATION="300M"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/configure-hardware.sh
# You can edit these values manually.

TTS_CPU_LIMIT=${CPU_LIMIT}
TTS_CPU_RESERVATION=${CPU_RESERVATION}
TTS_MEMORY_LIMIT=${MEM_LIMIT}
TTS_MEMORY_RESERVATION=${MEM_RESERVATION}

# TTS behavior
AUTO_DOWNLOAD_DEFAULT_PIPER_MODEL=${AUTO_DOWNLOAD_DEFAULT_PIPER_MODEL:-1}
DEFAULT_PIPER_VOICE_ID=${DEFAULT_PIPER_VOICE_ID:-en_US-lessac-medium}
EOF

echo "Detecting system hardware..."
echo "Architecture: ${ARCH}"
echo "Total RAM: ${TOTAL_MB} MB"
echo "CPU Cores: ${CORES}"
echo "GPU Type: ${GPU}"
echo ""
echo "Recommended Configuration:"
echo "  CPU Limit: ${CPU_LIMIT}"
echo "  Memory Limit: ${MEM_LIMIT}"
echo "  CPU Reservation: ${CPU_RESERVATION}"
echo "  Memory Reservation: ${MEM_RESERVATION}"
echo ""
echo "Configuration saved to ${ENV_FILE}"
echo "You can now run: podman-compose up -d"
